# Generated by Django 4.1.7 on 2023-02-18 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebyeapp', '0002_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
