# Generated by Django 4.1.7 on 2023-02-19 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebyeapp', '0005_product_mrp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='category',
            new_name='Categ',
        ),
        migrations.AlterModelOptions(
            name='categ',
            options={'ordering': ('name',), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
