# Generated by Django 4.1.7 on 2023-02-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebyeapp', '0006_rename_category_categ_alter_categ_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categ',
            options={'ordering': ('priority',), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='categ',
            name='priority',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
